---
title: "wk4_homework"
author: "Yutong Xu"
date: "2025-10-24"
output: html_document
---

# 1.Load packages

```{r}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(countrycode)
```

# 2.Read global gender inequality data

```{r}
gender_data <- read_csv(
  here("exam4_data", "HDR25_Composite_indices_complete_time_series.csv")
) %>% 
  clean_names()

names(gender_data)
```

# 3.Select required variables

```{r}
gii_clean <- gender_data %>% 
  select(iso3, country, gii_2010, gii_2019) %>% 
  mutate(
    iso2 = countrycode(iso3, "iso3c", "iso2c"),
    gii_diff_2019_2010 = gii_2019 - gii_2010
  )
```

# 4.Read world spatial data

```{r}
world <- st_read(
  here("exam4_data", "World_Countries_(Generalized)_9029012925078512962.geojson")
) %>% 
  clean_names()

names(world)
```

# 5.Spatial join

```{r}
world_gii <- world %>% 
  left_join(
    gii_clean,
    by = c("iso" = "iso2")   # world$iso (ISO2) 对上 gii_clean$iso2
  )

world_gii %>% 
  st_drop_geometry() %>% 
  select(iso, country.x, country.y, gii_2010, gii_2019, gii_diff_2019_2010) %>% 
  head(10)
```

# 6.Save output

```{r}
dir.create(here("output"), showWarnings = FALSE)

st_write(
  world_gii,
  here("output", "world_gii_2010_2019_diff.geojson"),
  delete_dsn = TRUE
)
```